### ISSUE TITLE
extensionOnImport - only if different file extension

### ISSUE THREAD

**Issue by donaldpipowitch** [ChristianKohler/PathIntellisense#10]
I'd would be nice if I could use

```
{
    "path-intellisense.extensionOnImport": true,
}
```

only if the file extension from the imported file is different from the importing file. Say I'm in `foo.ts` and want to import `bar.ts` and `baz.css` (in a webpack project). I want the `.css` extension, but not `.ts`.

**Comment by jole78** [comment]
Hey,
First of all a big thanks for making this extension, it has helped me a lot!

But...I think my problem might be related to this one.

The thing I'm seeing is that if I'm in a .jsx file and import a .js file the extension is added anyway. It might be good if the extension could treat .jsx and .js as the same file type (as well as .ts and .tsx I guess) or if this could be configured somehow, meaning that you could teach the extension which file types it should treat as the same thus not adding the extension to these imports.

Another solution might be to tell the extension which file types it should add extensions to and all others come without but that might be a breaking change compared to this issue.
