### ISSUE TITLE
${workspaceFolder} not working

### ISSUE THREAD

**Issue by seanmars** [ChristianKohler/PathIntellisense#115]
The variable ${workspaceRoot} was deprecated in favor of ${workspaceFolder} to better align with .

[Why isn't ${workspaceRoot} documented?](https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented)

**Comment by lunelson** [comment]
`${workspaceFolder}` works partly; but it still picks the first folder in the multi-root workspace, rather than the one that is the parent of the current file.
