### ISSUE TITLE
Add support for folder names starting with dot

### ISSUE THREAD

**Issue by Laureian** [ChristianKohler/PathIntellisense#12]
In my project i have folder '.Shared'(name starting with dot), because i want to have it on top. Extension didn't showing this folder in list. See attached gif(.Shared path: '../../.Shared/'):
![animation](https://cloud.githubusercontent.com/assets/6832706/16260827/583f6efc-3869-11e6-8d1b-a1825eb84bf4.gif)

**Comment by ChristianKohler** [comment]
Thank you @Laureian for reporting the bug. The reason why it doesn't work at the moment is, that PathIntellisense expects a . as first character. I added the check to make sure the import is relative from the current file. This is something I have to rethink anyway to enable functionality like #5

**Comment by ChristianKohler** [comment]
Fixed with v1.1.0. Thank you @Laureian
