### ISSUE TITLE
Works only if no characters entered in 1.3.0

### ISSUE THREAD

**Issue by dbettini** [ChristianKohler/PathIntellisense#14]
Extension shows the list of all deps after entering quotation marks. However, as soon as any character is entered (even if it's the first letter of a module name), all deps disappear completely and don't appear until you delete all characters and hit the suggestions command.

This happens with [NpmIntellisense](https://github.com/ChristianKohler/NpmIntellisense/issues/7) as well. I initially thought all similar extensions are broken in 1.3.0 and wanted to report it to [vscode](https://github.com/Microsoft/vscode), however [HTML/CSS Class Completion](https://github.com/Zignd/HTML-CSS-Class-Completion) works without a problem.

**Comment by ChristianKohler** [comment]
Thank you @dbettini

**Comment by donaldpipowitch** [comment]
It looks like I still have this problem in 1.3.0 with PathIntellisense. However NpmIntellisense does seem to work after an update.
