### ISSUE TITLE
show other files besides `*.js` files in js import statement

### ISSUE THREAD

**Issue by littlee** [ChristianKohler/PathIntellisense#151]
only `*.js` files are shown in hints when writing import statement in js file
```
import './' // only js files are shown
```

how to make it show other files, when working with a webpack project, I would like to import `*.css` files and image files

**Comment by aneeskodappana** [comment]
The plugin is great. but it does not show other files. 
for example
```
// src/App.js
import './' // no files are shown other than js
```
@ChristianKohler is there a way to show other files in a .js file import

**Comment by littlee** [comment]
@aneeskodappana Did you just steal my avatar 🌚

**Comment by lekhnath** [comment]
???

**Comment by AradAral** [comment]
It's strange that this isn't already possible, there should at least be a configuration option that allows you to selectively choose which file extensions you want shown in the suggestions list.

**Comment by ChristianKohler** [comment]
@AradAral I can import other files without problems. Are you on the latest version (2.5.0)?


<img width="568" alt="image" src="https://user-images.githubusercontent.com/4374178/143890865-87ddb347-d344-4469-bc8d-663cebf80b92.png">

**Comment by AradAral** [comment]
@ChristianKohler Thanks for the quick response.
I actually just tried this in a `.ts` file and it actually does work as you said:

![image](https://user-images.githubusercontent.com/26527405/143897126-07cad5ed-9450-4ff6-b1ab-89a58b79211f.png)

But in `.svelte` files, it doesn't:

![image](https://user-images.githubusercontent.com/26527405/143897289-acf930c3-c58f-4a06-be14-d27c3800dbea.png)

Does this have anything to do with your extension? Is there a configuration option or anything?

**Comment by ChristianKohler** [comment]
Works for me:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/4374178/143916581-c34d6c64-c232-4dc5-a470-d1d1e1a8256a.png">

Could you check if another extension is interfering?

**Comment by AradAral** [comment]
Oh I think you should install the [Svelte extension](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) first, and then try writing the import in a `<script>` tag like:
```svelte
<script>
    import {} from "./";
</script>
```

But good to know that it works without the extension.
> Could you check if another extension is interfering?

Could you please install the extension and see if it still works? Because if it doesn't once you install the extension, then we can infer from that that it's probably the Svelte extension interfering with this.

Thank you in advance.

**Comment by ChristianKohler** [comment]
@AradAral Just installed the svelte extension. I can confirm that with the svelte extension it doesn't work anymore. 

I guess their extension has a higher score. Nothing I can do here :-/ Maybe you can disable autocompletion in the svelte extension?

> Multiple providers can be registered for a language. In that case providers are sorted by their score and groups of equal score are sequentially asked for completion items. The process stops when one or many providers of a group return a result.

https://code.visualstudio.com/api/references/vscode-api
