### ISSUE TITLE
Conflicting with NpmIntellisense

### ISSUE THREAD

**Issue by dbettini** [ChristianKohler/PathIntellisense#17]
It seems that even after requiring relative paths, [NpmIntellisense](https://github.com/ChristianKohler/NpmIntellisense) gets activated, which in turn disables PathIntellisense.

Example:
I'm inside of header.ts and want to `require("./header.html")`. After typing`./`, I get the correct list:
`..`, `header.ts`, `header.html`. However, as soon as I type in any character, everything falls back to NpmIntellisense. That is, I get suggestions from npm packages, as if I just entered `require("")`.

I think NpmIntellisense should be completely disabled if the path starts with `.`.

Edit: I opened the issue here since PathIntellisense is the one that isn't working. However, NpmIntellisense is the one that should probably be fixed, so I opened an [issue](https://github.com/ChristianKohler/NpmIntellisense/issues/8) there too.

**Comment by ChristianKohler** [comment]
Fixed with https://github.com/ChristianKohler/NpmIntellisense/issues/8

**Comment by kumarharsh** [comment]
@ChristianKohler it's conflicting with npmIntellisense for me too, but only for cases when I define `path-intellisense.mappings`. For example, here is my mapping:

```json
"path-intellisense.mappings": {
    "components": "${workspaceRoot}/ui/src/components",
    "constants": "${workspaceRoot}/ui/src/constants",
    "css": "${workspaceRoot}/ui/src/css",
},
```

The PathIntellisense doesn't trigger when I type `constants/` in JS files, but does trigger when I type `css/` in css files. If I disable npmIntellisense, then I this plugin behaves correctly.
