### ISSUE TITLE
Doubling file path results

### ISSUE THREAD

**Issue by Soldr** [ChristianKohler/PathIntellisense#172]
![image](https://user-images.githubusercontent.com/66232265/111786250-f5c79580-8893-11eb-9094-b37a1d551002.png)

Version 2.3.0

**Comment by pingmouren** [comment]
You can use the following configuration to try
{
"javascript.suggest.paths": false,
  "typescript.suggest.paths": false,
}

**Comment by Sc-6-23** [comment]
> You can use the following configuration to try
> {
> "javascript.suggest.paths": false,
> "typescript.suggest.paths": false,
> }

but the setting
"path-intellisense.mappings": {
         "/": "${workspaceFolder}",
         "@": "${workspaceFolder}/src"
     }
"@" cannot take effect in the .js file

**Comment by ChristianKohler** [comment]
Thank you @pingmouren for the help

Closing the bug.
