### ISSUE TITLE
Add option to include default exports in autocomplete

### ISSUE THREAD

**Issue by lgarczyn** [ChristianKohler/PathIntellisense#173]
Vue and React both mostly use default exports for components, usually like this

```typescript
// Comp.[vue|react|ts|js]
export default class Comp extends Base {}
```

Other major libraries such as axios also use default exports.

Would it be possible to add a suggestion for any module with default exports, using the name of the file/module as the name of the imported class ?

The generated code would simply be this:

```typescript
import Comp from 'Comp.vue';
import axios from 'axios;
```

**Comment by ChristianKohler** [comment]
This extension completes paths. So you can use it in any import statement like

```
import { comp } from "./path/to/my/comp"
```

or with default imports as well:

```
import comp from "./path/to/my/comp"
```

If you are looking for an extension with creates the full. import statement, as @zardoy mentioned, typescript can do that out of the box.

Hope that helps.
