### ISSUE TITLE
Path Intellisense cannot work well in vue.js when use @ as path beginning identity

### ISSUE THREAD

**Issue by mebest100** [ChristianKohler/PathIntellisense#175]
Path Intellisense cannot work well in vue.js when use @ as path beginning identity, there is no any path hint any more.
This problem occurs at version 2.3.0,2.2.1,2.2.0

![image](https://user-images.githubusercontent.com/11530991/115132756-7dd8c080-a035-11eb-8010-cabf26fba3f0.png)

But when downgrade to version 1.4.2, it works again.

Pls help fix this problem. Thx!

**Comment by ChristianKohler** [comment]
Did you set the mapping in the setting? How does it look like?

**Comment by Sc-6-23** [comment]
Versions after 2.20 will conflict with the default path completion of vscode, causing the path prompt to appear repeatedly, when vscode is set
"typescript.suggest.paths": false,"
"javascript.suggest.paths": false"
The path prompt will not appear repeatedly, but the setting
"path-intellisense.mappings": {
         "/": "${workspaceFolder}",
         "@": "${workspaceFolder}/src"
     }
"@" cannot take effect in the .js file

**Comment by Sc-6-23** [comment]
This is a screenshot of duplicate path prompts:
![image](https://user-images.githubusercontent.com/73343288/134306478-d278bf0e-769f-4bbe-be22-7830a9bcad8d.png)
windows: 10,
vscode: v1.61
path intellisense: v2.4.0

**Comment by ChristianKohler** [comment]
Hey @mebest100 

Vue uses webpack to resolve.alias to set `@` to `src`.

The extension can do the same, but it has to be configured in the settings. Here is an example how it could look like:

```
"path-intellisense.mappings": {
      "@": "${workspaceFolder}/src"
}
```

Closing the issue since it should work with the correct setting. Let me know if it does not.
