### ISSUE TITLE
Markdown path suggestions includes many paths with dots (`..`)

### ISSUE THREAD

**Issue by rzhao271** [ChristianKohler/PathIntellisense#181]
In a markdown file, I typed the start of a path (i.e. `wiki`), and I get a lot of suggestions that want me to back out of the directory again for some reason (e.g. `../api`):

![dots-in-paths](https://user-images.githubusercontent.com/7199958/119018429-ebd41880-b950-11eb-8d7d-341a1d1627f8.png)

Maybe the option to include sibling directories can be placed behind a setting, since I notice on the `vscode-docs` repo on Codespaces, the performance of the extension seems a bit slow from always showing all of these paths.

**Comment by ChristianKohler** [comment]
Can you reproduce with PathIntellisense disabled?

**Comment by rzhao271** [comment]
I think I was still able to reproduce the issue, but I'll just close this issue now since adding `{ "key": ".", "command": "" }` to the keybindings stopped it.
