### ISSUE TITLE
path completion of vscode is duplicate

### ISSUE THREAD

**Issue by Sc-6-23** [ChristianKohler/PathIntellisense#189]
Versions after 2.20 will conflict with the default path completion of vscode, causing the path prompt to appear repeatedly, when vscode is set
"typescript.suggest.paths": false,"
"javascript.suggest.paths": false"
The path prompt will not appear repeatedly, but the setting
"path-intellisense.mappings": {
         "/": "${workspaceFolder}",
         "@": "${workspaceFolder}/src"
     }
"@" cannot take effect in the .js file
This is a screenshot of duplicate path prompts:
![image](https://user-images.githubusercontent.com/73343288/134306478-d278bf0e-769f-4bbe-be22-7830a9bcad8d.png)
windows: 10,
vscode: v1.61
path intellisense: v2.4.0

_Originally posted by @Sc-6-23 in https://github.com/ChristianKohler/PathIntellisense/issues/175#issuecomment-924686307_

**Comment by ChristianKohler** [comment]
You can disable the default path completion with

```
{ "typescript.suggest.paths": false }
{ "javascript.suggest.paths": false }
```

hope that helps.
