### ISSUE TITLE
Add Path mapping

### ISSUE THREAD

**Issue by m0n01i7h** [ChristianKohler/PathIntellisense#19]
It would be great to have ability to use path mapping like webpack `resolve.root` or [TS 2.0] paths (https://github.com/Microsoft/TypeScript/issues/5039)

Example workspaceSettings.json
```json
...
"path-intellisense.paths": {
  "~": "${workspaceRoot}/",
  "server": "${workspaceRoot}/server",
  "myLib": "${workspaceRoot}/../my-lib"
},
...
```

It looks like simple replacement 
```
  if path starts with oneOfKeys 
    replace oneOfKey with oneOfValue in path
```

**Comment by jole78** [comment]
Agreed. I have a folder structure like root/client/app_1, root/client/app_2 and so on. I have already made this work with webpack by adding aliases for app_1 and app_2 so I can import like:

`import {something} from app_1/some_module`

...but it would be great if the extension could also pick this up so I can write 'app_1/' and it starts there and shows my the modules.
Or...maybe it could work like if I start by writing '/client/' and then it strips off the client part when done...?? via a setting of course.

**Comment by kumarharsh** [comment]
Actually, there is a webpack config setting [`resolve.modulesDirectories`](https://webpack.github.io/docs/configuration.html#resolve-modulesdirectories) where we can specify custom folders which can become module directories, and we can import from them just like we do node-modules. A support for this will be fantastic as well, although I'm not sure about the perf impact yet.
