### ISSUE TITLE
PathIntellisense not autocomplete

### ISSUE THREAD

**Issue by StefanoPernat** [ChristianKohler/PathIntellisense#20]
Hello since I update to the latest version when I type something after / the PathIntellisense don't autocomplete and the standard visual studio intellisense will show up,

**Comment by gornikp** [comment]
add . at the beginning like "./css/app.cs"

**Comment by bddenhartog** [comment]
@gornikp That is not an absolute path. See #5.

**Comment by ChristianKohler** [comment]
@StefanoPernat: Do you still have issues with PathIntellisense?

**Comment by StefanoPernat** [comment]
@ChristianKohler Now it seems to work fine thanks

**Comment by ChristianKohler** [comment]
Great. Thank you @StefanoPernat for your feedback.
