### ISSUE TITLE
Not working under remote ssh since vscode 1.65.0 release

### ISSUE THREAD

**Issue by renkun-ken** [ChristianKohler/PathIntellisense#200]
The path completion works properly on local machine but no longer works under remote ssh since vscode 1.65.0 release. Looks like it works in the latest insider again. Not sure what has caused this and has been fixed for this.

**Comment by ChristianKohler** [comment]
Thank you @renkun-ken 

Do you see any errors in the devtools?

**Comment by renkun-ken** [comment]
It is fixed in Path-Autocomplete in https://github.com/ionutvmi/path-autocomplete/issues/108. Not sure if the same applies here?

**Comment by ChristianKohler** [comment]
> 

Might be the same root cause. But from the error and the fix I can't see what caused the issue and how it applies to this extension. 

If you have any errors in the devtools, that would be super helpful as a first step to narrow it down.

Thanks for you help.
