### ISSUE TITLE
Add support for absolute file system paths

### ISSUE THREAD

**Issue by TeaDrivenDev** [ChristianKohler/PathIntellisense#22]
When working with data in a REPL driven style, the files to process will not necessarily be located in a specific location relative to the code file, and maybe (on Windows) not even on the same drive. It would be great to have support for globally absolute paths for those scenarios.

**Comment by ChristianKohler** [comment]
@TeaDrivenDev I am figuring out what's the best way to solve this. I would like to add a root folder setting as proposed in #5. This way i could resolve 

`import bla from '/{tab}'`

to the defined root folder. In your case this should open the root tree of your file system.

Do you have an idea how to make you scenario work well together with #5 ?

**Comment by TeaDrivenDev** [comment]
I do think using such a root folder setting for that would work - with the one big caveat that Windows still has no absolute file system root, so that would only allow for using one particular drive at a time with this. I suppose a lot of the time that wouldn't be a huge practical issue, but it would be an inherent limitation.

However, Windows absolute paths are very easy to detect on their own, but that would admittedly require its own code, largely independent of #5.

**Comment by ChristianKohler** [comment]
With v1.1.0 you have the ability to define mappings. This should resolve this issue. Thank you @TeaDrivenDev for your feedbak.
