### ISSUE TITLE
Outdated readme advice breaks the editor on latest version

### ISSUE THREAD

**Issue by dannymcgee** [ChristianKohler/PathIntellisense#220]
Hi there! There's currently some advice in the README for Windows users that appears to be no longer applicable, and (more importantly) causes the editor to stop functioning normally on the latest 1.78.0 release:

> There is an issue on windows with the period key. See Issue https://github.com/ChristianKohler/NpmIntellisense/issues/12
> 
> Add this to the keybinding:
> ```json
> { "key": ".", "command": "" }
> ```

Following this advice causes all `.` keypresses within the editor to [trigger a "command '' not found" alert](https://github.com/microsoft/vscode/issues/181469#issuecomment-1539704904), and prevents the `.` character from being typed anywhere in the editor. Furthermore, removing the suggested binding doesn't seem to have any adverse consequences (on 1.78.0 and Windows 11, at least) — the extension's path suggestions continue working as expected.

On a related note: Is the extension automatically adding that binding to users' `keybindings.json` by chance? I took a quick look around and couldn't find anything to that effect, but I was affected by the linked issue and I don't remember ever adding that binding myself. (But I have been using this extension for a long, long time, so it's possible I added it at some point and promptly forgot about it.)

**Comment by starball5** [comment]
Apparently the fix can be made on VS Code's side and it will be available in 1.78.2 ([source](https://github.com/microsoft/vscode/issues/181469#issuecomment-1542148069)).

**Comment by dannymcgee** [comment]
> I don‘t have a windows environment to test. Since the issue was resolved with 1.78.2, could you quickly test if it works again and let me know?

I can confirm that adding the `{ "key": ".", "command": "" }` keybind has no apparent adverse effect in 1.78.2, but I can also confirm that Path Intellisense works the same with or without it. 🙂

**Comment by ChristianKohler** [comment]
Great. Thank you for checking @dannymcgee
