### ISSUE TITLE
Not auto-completing when in the middle of a word

### ISSUE THREAD

**Issue by jerrygreen** [ChristianKohler/PathIntellisense#222]
It works when previous symbol is `/`, but if you start in the middle of a word, it doesn't work.

Gif:
![gif2](https://github.com/ChristianKohler/PathIntellisense/assets/13215662/aecf952f-62ed-4dea-a02a-3a2a63dd338b)

**Comment by ChristianKohler** [comment]
Duplicate of https://github.com/ChristianKohler/PathIntellisense/issues/150

Unfortunately , I don‘t see a way how to make that work.
