### ISSUE TITLE
Ask for helpling how to enter /mnt

### ISSUE THREAD

**Issue by mckim05** [ChristianKohler/PathIntellisense#225]
Even with Path Intellisense installed, absolute path typing doesn't work.
For example, if I tried to type target_forder = '/mnt', I expected it to autocomplete if I just typed '/m'.
I already tried changing settings.json as below but it doesn't work.
      "path-intellisense.mappings": {
      "/mnt":"${workspaceFolder}/mnt"
      },

Please share what to do.

**Comment by ChristianKohler** [comment]
Can you try it without the leading `/`? Just `mnt`

**Comment by mckim05** [comment]
Hi
I tried as your comment, without using /, but it doesn’t work as well.

But when I use /m , it represent folder path what I have.

![IMG_6179](https://github.com/ChristianKohler/PathIntellisense/assets/122076276/bfe7ba14-cb94-4f8e-b5b1-be1ce76e32e2)

**Comment by ChristianKohler** [comment]
Good to hear. Thank you for letting me know. Closing the issue.
