### ISSUE TITLE
path-intellisense.mappings not work perfect with scss

### ISSUE THREAD

**Issue by ccqgithub** [ChristianKohler/PathIntellisense#235]
Add these config to settings.json:

```json
"path-intellisense.mappings": {
    "@/": "${workspaceFolder}/src",
    "~@/": "${workspaceFolders}/src"
  }
```

No intellisense with the `@use`:

```scss
@use "@/";
```

use path-autocomplete extenstion, it work:

```json
"path-autocomplete.pathMappings": {
    "@": "${folder}/src",
    "~@": "${folder}/src"
  }
```

**Comment by ChristianKohler** [comment]
Thx for feedback. Should be working with the latest version (2.10) with tsconfig directly (without mappings). Will close the issue for now. If v2.10 with tsconfig.path support is not what you are looking for, please feel free to open the issue again.
