### ISSUE TITLE
Remove the tail when path is applied

### ISSUE THREAD

**Issue by moander** [ChristianKohler/PathIntellisense#24]
When adding a new import I often make a copy of an existing line

```html
<link rel="import" href="../bower_components/paper-styles/color.html">
<link rel="import" href="../bower_components/paper-styles/color.html">
```

Then I modify the path 
```html
<link rel="import" href="../bower_components/paper-styles/color.html">
<link rel="import" href="../bower_components/paper-styles/sha<TAB>.html">
```

Now I have two .html extensions ;)
```html
<link rel="import" href="../bower_components/paper-styles/color.html">
<link rel="import" href="../bower_components/paper-styles/shadow.html.html">
```

When the completed path is a directory the tail should be preserved, but when the path is a file it should remove that extra stuff on the right side of the cursor.

**Comment by ChristianKohler** [comment]
Thank you @moander for your feedback. Good idea. I have to think about some special cases like a file with two dots but i guess it could work if I just remove everything on the right side of the cursor  to the quotation marks. I'll try to add the enhancement in the release.

**Comment by ChristianKohler** [comment]
@moander I tried to implement this but couldn't find a way to remove code. I seems that a plugin only can add code not delete it. I close the issue since I don't see a way to implement it at the moment.
