### ISSUE TITLE
Support Typescript 2's baseUrl setting

### ISSUE THREAD

**Issue by Elarcis** [ChristianKohler/PathIntellisense#27]
Typescript 2 includes a baseUrl option in its tsconfig.json.

This option specifies the base path (relative to tsconfig.json) from which non-relative modules are imported (without conflicting with node_modules and such).

It could be nice for PathIntellisense to support this as well.

Example:

``` Typescript
import { MyClass } from 'api/myModule'; // here, api folder is at the root of the project, though we can import it with this syntax from anywhere.
```

**Comment by ChristianKohler** [comment]
Hi @Elarcis, thank you for the feedback. Would be nice to support ts2 baseUrl. At the moment it would collide with https://github.com/ChristianKohler/NpmIntellisense thought. We need to figure out what should be suggest when the string is empty:

`import {} from ''`

At the moment it displays npm packages.

**Comment by kasperekt** [comment]
@ChristianKohler I think it should display TS2 baseUrl files first, then npm packages.

**Comment by ChristianKohler** [comment]
@Elarcis I added a new option "Mapping". See: https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense. So you can add a mapping for an "api" folder. What do you think?

**Comment by Elarcis** [comment]
While it is a nice addition and will indeed serve for webpack mappings (thanks!), I still think a 'default' support for `baseUrl` is necessary, as it'll make quite a lot of duplicated configuration if we have lots of modules in the folder pointed by it (currently five, and it's varying moderately quick)

**Comment by ChristianKohler** [comment]
Hi @Elarcis, i added basic support for baseUrl to version 1.3. Please let me know if it works as expected. Thank you.

**Comment by Elarcis** [comment]
Thanks for considering my demands @ChristianKohler. I confirm that my folders situated in the root folder appear in the suggestion list.

However, npm packages still appear in the list even when I start going into subfolders, where these package aren't available and thus shouldn't appear.

e.g;
```
import {} from 'a' // proposes the 'api' folder as well as angular, angular-cookies, etc.
import {} from 'api/' // proposes the folders contained in 'api', but still proposes as well angular, angular-cookies, etc.
```

Thanks for taking time to implement the feature anyway, I really appreciate it!

**Comment by ChristianKohler** [comment]
@Elarcis Thank you for your quick feedback. Happy that it works in general. It shouldn't suggest angular after you typed 'api/'. This is a bug in NpmIntellisense. I'll add a new issue in NpmIntellisense.
