### ISSUE TITLE
Doesn't work when the path is surrounded with backticks

### ISSUE THREAD

**Issue by Ygilany** [ChristianKohler/PathIntellisense#29]
apparently it only works when I use single ' or double quotes " but it doesn't even get triggered if I use the backticks `

**Comment by ChristianKohler** [comment]
@Ygilany As far as I know, import statements are stringliterals. In which case would you use templateliterals?

**Comment by Ygilany** [comment]
@ChristianKohler we have an eslint rule where all strings should use backticks.. so stuff like this 

const Model_Cluster = require(`../../libs/ModelCluster`);

The auto complete wouldn't work in this case

**Comment by Ygilany** [comment]
@ChristianKohler

**Comment by ChristianKohler** [comment]
Thank you @Ygilany Your pr is merged and will be included with version 1.3
