### ISSUE TITLE
Dont work in vscode 1.6

### ISSUE THREAD

**Issue by Ysuran** [ChristianKohler/PathIntellisense#30]
With the last version (vscode 1.6) the extensión not work

**Comment by ChristianKohler** [comment]
@Ysuran Thank you for the report. I am investigating the problem at the moment.

**Comment by ChristianKohler** [comment]
@Ysuran I just published 1.1.0. Could you check whether the plugin works now with vscode 1.6?

**Comment by Ysuran** [comment]
Sorry but no. The extension does not work

**Comment by Learn-Digital-Audio** [comment]
it's not working here either.

**Comment by Ysuran** [comment]
Hello again. After rebooting my pc the extension works fine again.
Good job.
The firt time only update the extension but do not restart the pc.

**Comment by Learn-Digital-Audio** [comment]
LOL, you are right, it's fine after reloading! Maybe mention that in the docs?

**Comment by djx339** [comment]
Restart also not working for me.

**Comment by ChristianKohler** [comment]
@djx339 I can not reproduce the bug on my system. Could you open the developer tools (Help>Toggle Developer Tools) and look if there is an error in the console?

**Comment by yangg** [comment]
Here is the error on mac
```
main.js:1716 [1] - Grammar is in an endless loop - Grammar pushed & popped a rule without advancingscanNext @ main.js:1716
```
this is here is located at `/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/vscode-textmate/release/main.js`

**Comment by djx339** [comment]
@ChristianKohler I can't find any error, but have a waring. https://github.com/Microsoft/vscode/issues/13640#issuecomment-253690469 is my screenshot.

**Comment by Madebym** [comment]
Doesn't work for me either. Win7 32bit and Win1064 bit. It just says "no suggestions" when tyring to complete paths.

No errors in the console, just one warning, unrelated to your extension. Something with keybindings for auto-close html extension.

**Comment by djx339** [comment]
works after upgrade VSCode to 1.6.1

**Comment by alexandrudima** [comment]
The endless loop grammar error does not have anything to do with intellisense, it is detected and logged when a TextMate grammar is incorrect. Please find the body of text that reproduces this message and file a spearate issue against VSCode or against the repo that contains the truth for the grammar that VSCode uses for the respective language.
