### ISSUE TITLE
Support Custom Mapping with Placeholders/Globbing

### ISSUE THREAD

**Issue by ford04** [ChristianKohler/PathIntellisense#35]
Hi,
it would be nice if custom mapping could support placeholders/globs.

Say we have the folder structure, where "app" lies in the working dir root:
![image](https://cloud.githubusercontent.com/assets/16099458/19734409/b50e52f0-9ba7-11e6-8ad1-b86f4b9ec8cc.png)

If it is required that you specify urls relative to "app" as the root, i would like to add the following mapping:

`"*": "${workspaceRoot}/app/*"`

When I type `core` as the begin of the url, the plugin would map this to `${workspaceRoot}/app/core`.

Cheers

**Comment by ChristianKohler** [comment]
I like the idea. It is already possible with the existing custom mapping. What you can do is:

`"/": "${workspaceRoot}/app/"`

What would be the advantage of having the * instead of the / character for you?

**Comment by flexxis** [comment]
If I take you suggested approach, I have to type `/core` in my `templateUrl` to actually find everything under the core-folder. But in my case the url `core/xxx` (without leading slash) is expected.

Basically it would be useful to distinguish between the path mapping expression `"*": "${workspaceRoot}/app/*"` and the actual path defined in the code (like `core/account.service.ts`).

The asterisk * could serve as a placeholder in the left and right side of the path expression (and only there, not in the code). Then you could compare the left-hand side of the path expression with the code path in the corresponding directory.
