### ISSUE TITLE
Optionaly leave out extension when importing

### ISSUE THREAD

**Issue by minedeljkovic** [ChristianKohler/PathIntellisense#4]
First of all, thank you for this really helpful extension.

It is common to leave out extension on js file when doing import or require.
e.g.
Path: 
```
./some-folder/someFile.js
```
Code: 
```js
import {something} from './some-folder/someFile';
```

Would you agree to make this default behavior of extension, or at least define a setting for this?
Would you include this, or accept PR for this?

**Comment by ChristianKohler** [comment]
Thank you @minedeljkovic for the idea. I just implemented the feature: https://github.com/ChristianKohler/PathIntellisense/commit/e0cf5a11d56119a78019589ec1581fa4fcf148c8
