### ISSUE TITLE
Add support for environment variables in the path.

### ISSUE THREAD

**Issue by hashhar** [ChristianKohler/PathIntellisense#40]
Add support for paths like `$HOME/.local/bin` etc.

**Comment by ChristianKohler** [comment]
Hi @hashhar, could you elaborate on this issue? What's your use case for this feature? Thanks

**Comment by hashhar** [comment]
I use to write a lot of shell scripts and come across paths that have a variable like `$HOME/.local/bin`. Your extension works if I write `/home/ashhar/.local/bin` but I was wondering if there was a way to resolve environment variables too. Apparently environment variables are also passed down to VSCode's extension host and hence you should be able to resolve them theoretically.

It's not a major issue and isn't worth implementing if it introduces too much complexity or isn't wanted by many people.
