### ISSUE TITLE
Add Support for absolute paths

### ISSUE THREAD

**Issue by LarsKoelpin** [ChristianKohler/PathIntellisense#45]
At the current state of the extension, absolute paths do not get detected, tho i
feel like I'm missing this feature sometimes ("/" would sugest me files from the current directory, tho it is an absolute path).

On my local Debian System, I fixed it as a "works for me"-algorithm by simply checking
if the string starts with a "/"  (Root of the filesystem) and there is no other "/" left (so one can actually navigate). This does not work for Windows systems and - of course - is not the best solution for this problem.
 
```typescript
   provide(fileName, textWithinString, mappings, isImport, documentExtension) {
        const path = getPath(fileName, textWithinString, mappings);
        if(textWithinString.startsWith("/") && textWithinString.lastIndexOf("/") == 0) {
            // absolute path, so start at "/"
            return this.getChildrenOfPath("/").then(children => ([
              new UpCompletionItem(),
              ...children.map(child => new PathCompletionItem(child, isImport, documentExtension))
            ]));
        }```

It would be nice to find a general solution for this.

**Comment by henrikra** [comment]
I am using absolute paths in my React Native project and I just added this to my `settings.json`:
```
"path-intellisense.mappings": {
    "src": "${workspaceRoot}/src"
}
```
This way I can get PathIntellisense to suggest files from src folder which is inside or my project root. :)

**Comment by orenklein** [comment]
+1
@henrikra What if your workspaceRoot is the src? You don't want to map every folder in the src.
