### ISSUE TITLE
Latest VSC added IntelliSense for paths

### ISSUE THREAD

**Issue by henrikra** [ChristianKohler/PathIntellisense#47]
Like you can see here: https://code.visualstudio.com/updates#_javascript

So my question is that is this plugin still needed? :D

**Comment by Maroon1** [comment]
but this plugin faster than native.

**Comment by lironess** [comment]
Where did you see it? is it `emmet.extensionsPath` ? and how do I use it? can you provide an example please?

**Comment by ChristianKohler** [comment]
This plugin works with every language / filetype. I don't need it anymore for Typescript thanks to their auto import feature. But there are still many cases where I am glad to have path intellisense.

**Comment by p4trykJ** [comment]
@ChristianKohler Can u please spot most important differences betweeen VSC native path intellisense feature and this plugin?
