### ISSUE TITLE
Allow usage of Absolute File Path

### ISSUE THREAD

**Issue by dcernach** [ChristianKohler/PathIntellisense#5]
Hello, 

Firstly, many thanks for this extension. It's great...
Secondly, I would like to suggest you an improvement to this extension by allowing the possibility of absolute path autocomplete (relative to project root folder). Many developers prefer using absolute path to their file paths (me included). It makes your life easier when you decide to move the things around.

<link rel="stylesheet" type="text/css" href="../../content/styles/site.css" />
- vs - 
<link rel="stylesheet" type="text/css" href="/content/styles/site.css" />

Bye,
Dalton Andrade

**Comment by ChristianKohler** [comment]
Thank you.

Absolute paths would be helpful for html tags like:

`<img src="images/main.gif">`

Do you have anything else in mind. ES import are usually relative path.

**Comment by vuhrmeister** [comment]
First of all: thx, great extension.

I would also like to see support for absolute paths. I actually use absolute paths for ES import statements.

**Comment by pesho** [comment]
> @ChristianKohler your example is actually a relative path, not absolute. An absolute path looks like:

This depends on the language used. In your examples you used HTML where indeed `"dir/file"` is a relative path. In other languages/platforms, for example Node.js `"dir/file"` should be considered an absolute path, within `node_modules` or anything in `$NODE_PATH`.

**Comment by ChristianKohler** [comment]
v1.1.0 support custom mappings. Just add a mapping for '/' to the current workspace folder and you have an absolute path. I'll close the issue. Thank you all for the input.

**Comment by ctumolosus** [comment]
@ChristianKohler can you use mappings to complete paths in `node_modules` directory? I was only able to map specific packages. (e.g. configuring mapping settings with `{ "material-ui": "${workspaceRoot}/node_modules/material-ui" }` would assist with path completion when importing `material-ui` package, but I would like assistance when referencing *any* package in `node_modules`)
