### ISSUE TITLE
Obey editor.quickSuggestions setting

### ISSUE THREAD

**Issue by W4RH4WK** [ChristianKohler/PathIntellisense#52]
I really like this extension, but it keeps popping up as soon as a `/` is typed.

I have `editor.quickSuggestions` set to `false` since I'd like to manually trigger autcompletion when I need it. This extension should also check this setting and only show the autocompletion popup if it's set to `true`.

**Comment by ChristianKohler** [comment]
Thank you opening the issure and opening one on Microsoft/vscode as well. Makes sense to implement the check. I have to check how what the best way is to set it.

**Comment by W4RH4WK** [comment]
@ChristianKohler from what I have seen so far, there is not much you can / should do about this. It should be handled by VSCode itself.

One option would be to only set the *trigger characters* if `editor.quickSuggestions` is `true` but this is not exactly what we want. If they decide to implement my suggestion this (and other) extensions should no longer experience this issue without any modification required. And if they decide against the change, things should probably be kept as they are.

**Comment by W4RH4WK** [comment]
Apparently there is already a dedicated option for *trigger characters*, `editor.suggestOnTriggerCharacters`. This solves this issue completely.
