### ISSUE TITLE
Hidden files shown in suggestions

### ISSUE THREAD

**Issue by bgoerdt** [ChristianKohler/PathIntellisense#54]
I have `path-intellisense.showHiddenFiles` set to false, but hidden files are still shown in the suggestions.

I am hiding JavaScript files that were transpiled from a TypeScript file using the following rule in my settings:
`"files.exclude": { "**/*.js": {"when": "$(basename).ts"}, "**/*.js.map": true }`

but the JavaScript still show up in the intellisense suggestions:

![image](https://cloud.githubusercontent.com/assets/3527455/23662688/fa9fe0c4-0315-11e7-9394-243366f12207.png)

**Comment by ChristianKohler** [comment]
hi @bgoerdt, thank you for you input. At the moment hidden files are only files with a dot prefix. But I like the idea to exclude this files as well. I added a new issue for this feature and I will close this one. #65
