### ISSUE TITLE
Have to using dot-slash to getting result

### ISSUE THREAD

**Issue by dehghani-mehdi** [ChristianKohler/PathIntellisense#55]
Hello,

Open up a folder contains `index.html` & `/sass/skin.scss`. (I'm using latest version of `VSCode`)

![sass](https://cloud.githubusercontent.com/assets/9152330/23822094/7a271712-065a-11e7-8db6-2a3b83e35eca.gif)

**Comment by ChristianKohler** [comment]
@dehghani-mehdi Which version are you using? Could you update to the newest version and check whether you still have the same issue? Closing this. Please reopen if problem still occurs with latest version. Thank you.

**Comment by dehghani-mehdi** [comment]
@ChristianKohler I could not reopen the issue.

Yes, the problem still exist in latest version.
`VS Code version`: __1.12.1__
`Path Intellisense version`: __1.3.0__
