### ISSUE TITLE
go to definition on mapped absolute paths

### ISSUE THREAD

**Issue by talarari** [ChristianKohler/PathIntellisense#58]
as many others, we use absolute paths a lot in our codebase to avoid '../../../' paths and to alias project specific "modules" (e.g import configuration from 'modules/configuration')

mapping 'modules' to its folder works great for auto complete, but doesn't support clicking into (go to definition) on paths.

is this supported? if not, is this something you might consider implementing?

**Comment by orenklein** [comment]
It's easy to solve that using jsconfig/tsconfig.
As vs code documentation mention - 

> jsconfig.json is a descendent of tsconfig.json, which is a configuration file for TypeScript. jsconfig.json is tsconfig.json with "allowJs" attribute set to true.

https://code.visualstudio.com/docs/languages/jsconfig#_jsconfig-options

You can create a jsconfig.json file at the root of your workspace:

```
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "baseUrl": "."
    },
    
    "exclude": [
        "node_modules",
    ]
}
```

I'd say that the most important parameters for your scenario are **exclude, baseUrl, paths**

**exclude**

> You will want to exclude files generated by a build process (for example, a dist directory). These files will cause suggestions to show up twice and will slow down IntelliSense.

**baseUrl**

> Setting baseUrl informs the compiler where to find modules. All module imports with non-relative names are assumed to be relative to the baseUrl.

https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url

**paths**
if you want to map paths that are not directly located under baseUrl. 
For example, let's say your modules folder is located under projectRoot/app:

projectRoot
├── someFolder1
│   ├── someFile.js
│   └── someFile2.js
├── app
       ├── someFolder2
      └── modules
            └── configuration.js
            └── logging.js

And you want to be able to get IntelliSense for imports from "modules/*".
Add paths to jsconfig.json under compilerOptions as following -
```
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "baseUrl": ".",
        "paths": {
                "modules/*": ["app/modules/*"]
        }
    },
    
    "exclude": [
        "node_modules",
    ]
}
```

Now "import configuration from "modules/configuration" IntelliSense will work like a charm.
For further information about tsconfig/jsconfig and other options check the above mentioned links.

**Comment by talarari** [comment]
works great, thanks!

**Comment by nermolov** [comment]
I have the below as my `jsconfig.json` and Intellisense works for writing new imports and hinting as you work with imported modules, but I still can't jump to the defining file, anything I'm missing?

`jsconfig.json`
```
{
  "compilerOptions": {
    "baseUrl": "."
  }
}
```

Example import
```
import ErrorDisplay from 'src/components/forms/layout/ErrorDisplay'
```

Example imported file `src/components/forms/layout/ErrorDisplay.jsx`
```
import PropTypes from 'prop-types'

function ErrorDisplay ({ name }) {
  return null
}

ErrorDisplay.propTypes = {
  name: PropTypes.string
}

export default ErrorDisplay
```

**Comment by LordLovelysmell** [comment]
Not working for me as well as for @nermolov.
