### ISSUE TITLE
node_modules support

### ISSUE THREAD

**Issue by ya-kostik** [ChristianKohler/PathIntellisense#6]
Can you add support to autocomplete paths from custom folder like node_modules?

Regards.

**Comment by ChristianKohler** [comment]
HI @ya-kostik 

I created an other plugin which auto completes npm modules:
https://marketplace.visualstudio.com/items?itemName=christian-kohler.npm-intellisense

Is this plugin what you are looking for?

**Comment by ya-kostik** [comment]
Thank you, @ChristianKohler!
Yes, this is what i'm looking!
