### ISSUE TITLE
Add an option to configure quotation mark style

### ISSUE THREAD

**Issue by nikolaymatrosov** [ChristianKohler/PathIntellisense#61]
It would be great if I could configure what quote marks to use in imports.

**Comment by ChristianKohler** [comment]
Are you using typescript? If you use the ts import statement, the quotations has nothing to do with Pathintellisense. PathIntellisense only looks up the path. The user has to type the import statement manually or use the ts import statement. I'll close the issue. Please let me know if I misunderstood your issue.
