### ISSUE TITLE
Support for TypeScript re-exports

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [ChristianKohler/PathIntellisense#67]
Completion doesn't work with TypeScript re-exports ([source](https://www.typescriptlang.org/docs/handbook/modules.html)).
Code sample:
```ts
export { SomeClass } from "./dir/to/my-file";
export * from "./dir/to/my-file";
```

**Comment by ChristianKohler** [comment]
@GiedriusGrabauskas Which version do you use? This should work in the latest version.

**Comment by GiedriusGrabauskas** [comment]
Path Intellisense `1.4.1` with Visual Studio Code `1.12.1`.

**Comment by ChristianKohler** [comment]
There was a bug in 1.4.0. Could you update to 1.4.2 and check whether this fixes this issue?

**Comment by GiedriusGrabauskas** [comment]
Ok, now it's working. 👍
