### ISSUE TITLE
Nothing works after updating to 1.4.0, infinite path problem

### ISSUE THREAD

**Issue by dehghani-mehdi** [ChristianKohler/PathIntellisense#69]
Hi,

I just updated to v1.4.0, but:

![Screenshot](https://cloud.githubusercontent.com/assets/9152330/25863161/f4bb2288-34ff-11e7-887c-55084fd83040.png)

**Comment by sgal** [comment]
Same here - 1.4.0 is broken. Previous version works fine.

**Comment by ChristianKohler** [comment]
@dehghani-mehdi and @sgal I can not reproduce it on my machine. Could you post your PathIntellisense settings? Thank you.

**Comment by dehghani-mehdi** [comment]
@ChristianKohler I'm sorry man, I didn't get you, I didn't change anything and have not any specific setting for PathIntellisense. maybe @sgal can help you on this.

**Comment by gatimus** [comment]
Same here, Windows 10 x64. no custom settings.

**Comment by dreisen** [comment]
I'm still on 1.3.0 because one of my coworkers warned me that 1.4.0 was broken.
AFAIK just like the others he has no custom settings and the plugin shows the same erratic behavior that others are expieriencing

**Comment by dehghani-mehdi** [comment]
I just updated to 1.4.1, still same problem.

**Comment by akadop** [comment]
Same problem here as well.

**Comment by alecwhittington** [comment]
1.3.0 was working. No custom settings, just whatever is set by the extension during install. Upgraded to 1.4.0, immediately get the issues everyone else here is reporting. Upgraded to 1.4.1 and problem still persists. Just as the OP reported, it is only showing the contents of the current directory, does not traverse out of it no matter how many levels you go up, e.g. ../../../ - does not matter.

Latest version of VS Code, Windows 10 x64 (all updates current, not the Creators Update)

**Comment by dreisen** [comment]
I found out that if you enter a path, say "./img", hit escape and then ctrl + space, that it shows the correct folders/files inside "./img" again.

**Comment by msssk** [comment]
What is the build process? How can we check out the repo and install an older, working version?

**Comment by keesee** [comment]
Same here.  Just updated.  WIndows current, vsc 1.12, Path Intellisense 1.4.1.   it keeps giving you the option for your current folder. to go up ../../../../../../ and it never give you the file/folder options for the parent.

**Comment by keesee** [comment]
I tried the path autocomplete extension and it does work.   This extension seems to work better, but if users are needing a workaround until this issues is resolved search for the path autocomplete extension.

**Comment by ChristianKohler** [comment]
Working on it. Could reproduce on Windows. MacOs seems to work.

**Comment by ChristianKohler** [comment]
I pushed a fix with version 1.4.2. Could you test whether it fixes the issue?

**Comment by inosik** [comment]
v1.4.2 works again, thanks!

**Comment by dehghani-mehdi** [comment]
Great, it works, thanks @ChristianKohler. issue #55 solved too.

**Comment by ChristianKohler** [comment]
Great. Thank you @dehghani-mehdi @inosik for your help
