### ISSUE TITLE
does not seems to work with ES6 imports

### ISSUE THREAD

**Issue by mookraiser** [ChristianKohler/PathIntellisense#7]
I tried to use it in my JSX file (and reguar .js) without luck.
I typed

```
import a from './
```
followed by CTRL+SPACE

and a box say "no suggestions", I don't know if it is your plugin or "npm intellisense" that display that.

**Comment by ChristianKohler** [comment]
@mookraiser It should work with ES6 imports. "no suggestions" comes from vs code, not the extension. Could you make sure that you have the latest vs code and extension version.
