### ISSUE TITLE
No tip in 1.4.0.

### ISSUE THREAD

**Issue by wu38607** [ChristianKohler/PathIntellisense#71]
OS：ubuntu14

**Comment by ChristianKohler** [comment]
@wu38607  Thank you for posting the issue. Could be related to https://github.com/ChristianKohler/PathIntellisense/issues/66

Could you check the stack trace?

**Comment by wu38607** [comment]
Thank you for update 1.4.1,the  problem is solved.

**Comment by ChristianKohler** [comment]
@wu38607 Thank you for the feedback.
