### ISSUE TITLE
Everything seemed to work quite nicely in 1.4.2

### ISSUE THREAD

**Issue by oshalygin** [ChristianKohler/PathIntellisense#73]
Things seem to have broken themselves from the latest release.  Anyone else having issues?

**Comment by kumarharsh** [comment]
+1 - PathIntellisense doesn't work for me 99% of the time, though npmIntellisense does. Weird. I'm on Windows, v1.4.2.

**Comment by oshalygin** [comment]
latest release is solid, closing!  Thanks for all the hard work @ChristianKohler
