### ISSUE TITLE
Allow option to remove trailing forward slash in import statement completion item

### ISSUE THREAD

**Issue by eyalellenbogen** [ChristianKohler/PathIntellisense#8]
Hi,

When I type in an import statement and select a folder from the completion item list I it adds a trailing forward slash automatically. Then, in order to get the next completion item I need to hit ctrl+space. I think it'd be easier to remove the trailing slash and then instead of hitting ctrl+space you type the forward slash in. It's a little silly but in terms of usability it's one less keystroke. I think it'd be best to add a property in the settings to allow to control that.

Thanks!

**Comment by patrickburke** [comment]
Wouldn't it be even better of the completion simply didn't stop? So that after inserting the path, the completion list would still be visible but now contains the files and directories in that path.

I don't know if Code allows you to do that, but I think that would be the best solution...

**Comment by eyal453** [comment]
I've been playing with it and I don't think it's possible. The trigger is a character. Selection doesn't trigger another "provideCompletionItems". I wish it did in this case.

**Comment by ChristianKohler** [comment]
Yes, i couldn't find a way to trigger it again after the selection. Would be my prefered way too. But @eyal453 is right, it is cumbersome to hit ctrl+space for every completion. I'll either remove the trailing slash or make it optional.

Thanks @patrickburke and @eyal453 for your feedback.
