### ISSUE TITLE
Extensions are not hidden for .ts files

### ISSUE THREAD

**Issue by axxag** [ChristianKohler/PathIntellisense#85]
Hi there! Thanks for the great extension, it has been a lifesaver for me.

I am encountering an issue where .ts extensions are not hidden, but other extensions (like .tsx) are.

![path-intellisense-ts-ext](https://user-images.githubusercontent.com/8908634/27839404-cd0cfbea-60a5-11e7-992a-324380a8d54f.gif)

I have a collection of mappings configured (path-intellisense.mappings: {...}), but aside from that am using default settings. I am running the latest version (1.4.2 at the time of writing)

 I will take a crack at a PR for this when I get some time, but just wanted to let you guys know in advance.

**Comment by RyosukeCla** [comment]
This is the same thing for `.vue` file

```
import {} from 'components/ComponentA.vue'
```

**Comment by ccqgithub** [comment]
+1
