### ISSUE TITLE
No path intellisense for path-intellisense-mappings

### ISSUE THREAD

**Issue by dearsaturn** [ChristianKohler/PathIntellisense#88]
After installing VS Code on a fresh macOS (10.12.5) install, I'm no longer seeing path intellisense work for anything but relative paths.

Relevant configuration/info:

Project directories look like:

```
project/
    public/
        various/paths/to/js/files.js
```

jsconfig.json
```
{
    "compilerOptions": {
        "checkJs": true,
        "module": "es2015",
        "jsx": "react",
        "target": "es6",
        "baseUrl": "public/"
    },

    "exclude": [
        "public/assets",
        "./node_modules"
    ]
}
```

Workspace settings:
```
{
    "path-intellisense.mappings": {
        "assets": "public/assets",
        "css": "public/css",
        "fonts": "public/fonts",
        "images": "public/images",
        "img": "public/img",
        "js": "public/js",
        "scss": "public/scss"
    }
}
```

I'm using webpack+babel, and the root path of my webpack paths are all under `public/`. I used to see intellisense by typing `js/type-something-here`.

**Comment by dearsaturn** [comment]
Looks like this was just a conflict with `npm-intellisense`.

**Comment by vanhtuan0409** [comment]
I have the same issue
Can we do any things for this conflict

**Comment by meiliujun** [comment]
how to  use  "jsconfig.json"  mappings folder
