### ISSUE TITLE
Merge NpmIntellisense into this extension

### ISSUE THREAD

**Issue by eyalellenbogen** [ChristianKohler/PathIntellisense#9]
Hi again,

What do you think about merging your other extension (https://github.com/ChristianKohler/NpmIntellisense) with this one?

I think it makes sense to have one extension take care of import statements.

E

**Comment by donaldpipowitch** [comment]
I also use them together and have a problem: say I'd like to import a relative file and want to type `./` the `.` will trigger "accept" and accepts the first suggested npm module. I can't find the corresponding shortcut to change this behaviour :/

**Comment by dbettini** [comment]
@donaldpipowitch the solution is to unbind `.`. Add this to keybindings.json:
`{
        "key": ".",
        "command": ""
    }`

**Comment by ChristianKohler** [comment]
@dbettini Thank you for the hint. Didn't know that. I also added ".." as first suggestion which makes it even faster since you only have to hit enter.

**Comment by donaldpipowitch** [comment]
Awesome, thanks.

**Comment by ChristianKohler** [comment]
@eyalellenbogen: PathIntellisense is not just for import statements but for path completion in general. You can for example also autocomplete url in html src attributes. Also in a few years, npm could be replaced by another package manager while autocompletion for paths is something I don't expect to go away soon. This is why I created two extension separately.
