### ISSUE TITLE
VS Code now supports path suggestions

### ISSUE THREAD

**Issue by krokofant** [ChristianKohler/PathIntellisense#93]
https://code.visualstudio.com/updates/v1_17#_import-path-quick-suggestions-in-javascript-and-typescript

It could be added to readme how this module differs from VSCode's implementation.

**Comment by gnowland** [comment]
VScode now supports file path completion suggestions in HTML too!! (`<img src="...`, etc.)

https://code.visualstudio.com/updates/v1_21#_html-path-completion

So, as @krokofant said, can you put in readme how does this extension add any value beyond what is now built in?

Thanks!!

**Comment by emil14** [comment]
+1

would like to hear if I need this extension or not :)
