### ISSUE TITLE
Does not work in 1.17+

### ISSUE THREAD

**Issue by dyyylan** [ChristianKohler/PathIntellisense#94]
Thank for this great extension, I've been using it for a while and it has been working great.

Since the 1.17 update, it looks like the default IntelliSense tooltips are overriding what I have specified with path-intellisense. My config is super simple, just a single mapping like
`{ foo: '${workspaceRoot}/src' }`.

I can't seem to find any documentation on the new included path autocompletion and I haven't been able to figure out how to configure it to work the same way (if it is even supposed to at all), it will only give me autocompletion from my project root. I can't see the path-intellisense completion at all.

Is there some way to disable the default one, or to configure it to be able to alias folders like this extension does (thereby eliminating the need for it?)

**Comment by wesleymostien** [comment]
Doesn't work : 

  "path-intellisense.mappings": {
    "components": "${workspaceRoot}/src/components"
  },

**Comment by DrakeXiang** [comment]
And vscode's native path intelli is super slow, or only me?

**Comment by cadebward** [comment]
I downgraded my vscode. Works fantastic on 1.16. You can find the [download links for 1.16 here](https://code.visualstudio.com/updates/v1_16).

**Comment by dearsaturn** [comment]
I'm experiencing this too. Looks like I'm just gonna downgrade.

**Comment by dearsaturn** [comment]
Any luck with this, anyone?

**Comment by dyyylan** [comment]
I haven't found any solution @dearsaturn , still broken in 1.18 and I can't seem to find any workarounds or other extensions. It seems vscode should support this natively now but it doesn't give me any actual suggestions unless i remove the directory alias.

**Comment by dearsaturn** [comment]
@dyyylan is it also crushingly slow when you do that?

**Comment by dyyylan** [comment]
It's not too bad in my project of ~850 js files, only the first time that it loads up. Kind of useless to me though at the moment because all of our projects use webpack aliases for the js directory :(

**Comment by dearsaturn** [comment]
@dyyylan ours as well; both of our big projects use the relative root path of `projectRoot/app/...`

**Comment by chrishoage** [comment]
You can disable the vscode path suggestions which allows this plugin to work 

https://github.com/Microsoft/vscode/issues/35877#issuecomment-336583914

**Comment by dyyylan** [comment]
Cool, that configuration option is now live in 1.18.1, created a pull request to add that note to the readme.
