### ISSUE TITLE
在css样式表里使用url属性的时候不会自动感应文件路径

### ISSUE THREAD

**Issue by DLCnow** [ChristianKohler/PathIntellisense#96]
在css样式表里使用url属性的时候不会自动感应文件路径，但是在使用js引外部文件的时候可以正常使用src属性。
![image](https://user-images.githubusercontent.com/24190152/33117300-e5395f76-cfa2-11e7-8be9-1d8bf3b21864.png)
![image](https://user-images.githubusercontent.com/24190152/33117320-f68b7084-cfa2-11e7-824a-a641cebd1ed0.png)

**Comment by xubaoshi** [comment]
作者不是🇨🇳人，也看不懂你写的啊

**Comment by DLCnow** [comment]
I switch my operating system to macOS and the problem was resolved.
